language: csharp
mono:
  - alpha
solution: bl4n.sln
script:
  - wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -O .nuget/NuGet.exe
  - xbuild /p:Configuration=Release bl4n.sln
  - nuget install xunit.runner.console -Version 2.1.0 -OutputDirectory packages
  - mono ./packages/xunit.runner.console.2.1.0/tools/xunit.console.exe ./bl4n.Tests/bin/Release/BL4N.Tests.dll
  - mono ./packages/xunit.runner.console.2.1.0/tools/xunit.console.exe ./bl4ncui.Tests/bin/Debug/bl4ncuiTests.dll

